# Part of the code for this project was generated by ChatGPT.

import openai
import csv

openai.api_key = ""


num_iterations = 8552
train_file_path = "C:\\Users\\mikke\\Downloads\\cola\\train.tsv"
csv_file_path = 'generated_sentences2.csv'

with open(train_file_path, 'r') as train_file:
    next(train_file) 

    with open(csv_file_path, 'a', newline='', encoding='utf-8') as csv_file:
        writer = csv.writer(csv_file)
        
        for i, line in enumerate(train_file):
            if i >= num_iterations:
                break
            
            sentence = line.strip().split('\t')[3]
            label = line.strip().split('\t')[1]
            print("Original sentence: " + sentence)
            print("Original label: " + label)
            
            context_prompt = f"""
            You are tasked with creating sentences that test grammatical structures in English. Each sentence you generate should come with an evaluation of its grammaticality, labeled as either "1" which is acceptable or "0" which is unacceptable. Focus on variety in sentence complexity and structures, and ensure you challenge different grammatical rules.
            """

            generation_prompt = f"""
            Context: Use the sentence "{sentence}" to create a similar sentence that tests grammatical structures in English. 
            The new sentence should be labeled as either "1" which is acceptable or "0" which is unacceptable based on its grammaticality. Focus on variety in sentence complexity and structures.
            
            - Original: "{sentence}"
            The label of the original sentence is "{label}" and your sentence should be as well. If "{label}" is equal to 0, make sure the sentence is not grammatically correct. Be creative.

            Task 1: Generate a similar sentence.
            Task 2: Predict whether the new sentence is grammatically acceptable or not, based on standard English usage.

            Examples:
            - Generated Sentence: "She writes a letter every week."
            Judgement: 1
            - Generated Sentence: "If he would have known, he would have reacted differently."
            Judgement: 0
            
            Your output should be in this format:
            Generated Sentence:
            Judgement: 
            
            """

            response = openai.chat.completions.create(
                model="gpt-3.5-turbo-0125",
                messages=[
                    {"role": "system", "content": context_prompt},
                    {"role": "user", "content": generation_prompt},
                ],
                temperature=0.5,
                max_tokens=60,
                top_p=1.0,
                frequency_penalty=1,
                presence_penalty=0,
                seed=i
            )

            output = response.choices[0].message.content.strip()
            
            entries = output.split('Generated Sentence:')[1:]
            for entry in entries:
                try:
                    lines = entry.strip().split('\n')
                    if len(lines) < 2:
                        continue

                    generated_sentence = lines[0].strip('" ')
                    judgement = lines[1].strip().split(':')[1].strip()
                    judgement_value = int(judgement)
                    writer.writerow([generated_sentence, judgement_value])
                    print(f"Iteration {i}: Written to CSV - '{generated_sentence}', Judgement: {judgement_value}")
                except (IndexError, ValueError) as e:
                    print(f"Iteration {i}: Error processing entry: {str(e)}")
                    continue

            csv_file.flush()